name: Bug Report
description: Something is not working correctly
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug. Please fill in as much detail as possible.

  - type: input
    id: version
    attributes:
      label: Feedmix version
      description: Run `feedmix --version`
      placeholder: v0.5.0
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating system
      placeholder: Ubuntu 24.04 / macOS 14 / Windows 11
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: What happened?
      placeholder: Describe the bug and what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Run `feedmix feed`
        2. See error...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant output or error messages
      render: shell
